### ISSUE TITLE
Improved setText/setChar

### ISSUE THREAD

**Issue by ErikPech** [vedatori/Time-O-Mat#5]
the setChar and setText functions both turn the unnecessary LED's off and the necessary LED's on, but sometimes it would be better to turn the unnecessary LED's off and do nothing else,  this can be done by just removing the "setLED(segmentID, i, color);" line of code from the setChar function but I believe that @MarPta has the skills to do this better and more organized thus why I created this issue

**Comment by MarPta** [comment]
Done.

**Comment by MarPta** [comment]
Done
